source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in addressbook_client.gemspec
gemspec

group :development, :test do
  gem 'guard-rspec', '~> 4.7'
  gem 'rspec', '~> 3.7'
end
