# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.1'

gem 'actionpack', '~> 5.2.0'
gem 'activerecord', '~> 5.2.0'
gem 'activesupport', '~> 5.2.0'
gem 'railties', '~> 5.2.0'

gem 'dry-validation', '~> 0.12.0'
gem 'fast_jsonapi', '~> 1.2'
gem 'oj', '~> 3.6.3'
gem 'pg', '>= 0.18', '< 2.0'
gem 'puma', '~> 3.11'
gem 'rack-attack', '~> 5.3'
gem 'rack-cors', '~> 1.0'
gem 'tzinfo-data'
gem 'mimemagic'

gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  gem 'byebug'
  gem 'guard-rspec', '~> 4.7'
  gem 'rspec-rails', '~> 3.7'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry'
  gem 'rubocop', '~> 0.57.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'database_cleaner', '~> 1.7'
end
